---
title: "Class_Timelog"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(dplyr)
library(lubridate)
library(ical)
library(wesanderson)
library(scales)
library(lubridate)
```

```{r}
calendar_data <- "eek.ics" %>% 
  # Use ical package to import into R and then convert to "tibble" data frame format:
  ical_parse_df() %>% 
  as_tibble() %>% 
  # Use lubridate packge to wrangle dates and times. We'll do this later this semester:
  mutate(
    start_datetime = with_tz(start, tzone = "America/New_York"),
    end_datetime = with_tz(end, tzone = "America/New_York"),
    minutes = end_datetime - start_datetime,
    date = floor_date(start_datetime, unit = "day")
  ) %>%
  # Make calendar entry summary all lowercase:
  mutate(summary = tolower(summary)) %>% 
  # Do data wrangling to compute number of minutes and hours:
  group_by(date, summary) %>%
  summarize(minutes = sum(minutes) %>% as.numeric()) %>%
  mutate(hours = minutes/60) %>% 
  mutate(date = as.Date(date))
  calendar_data <- filter(calendar_data, date > 2000-01-01)
```

```{r}
View(calendar_data)
```

```{r}
ggplot(calendar_data, aes(x = date, y = hours, fill = summary)) + geom_col(
  position = position_dodge(preserve = "single")) + labs(
  x = "Date",
  y = "Hours",
  title = "Comparison of Class Work Hours",
  fill = "Class"
) + scale_fill_manual(values = c("#FF1053", "#11B5E4", "#8710A9", "#000000")) + scale_x_date(breaks = date_breaks("day"), labels = date_format("%b %d"))
```

```{r}
ggplot(calendar_data, aes(x = date, y = hours, fill = summary)) + geom_col(position = "fill") + scale_fill_manual(values = c("#FF1053", "#11B5E4", "#8710A9", "#000000"))
```

```{r}
ggplot(calendar_data, aes(x = hours, y = summary, fill = summary)) + geom_boxplot() + scale_fill_manual(values = c("#FF1053", "#11B5E4", "#8710A9", "#000000"))
```

```{r}
date_summary <- calendar_data %>% 
  group_by(date) %>% 
  summarize(total_work_time = sum(hours))

date_summary

ggplot(date_summary, aes(x = date, y = total_work_time, fill = "#0FFFBB")) + geom_col() + scale_fill_manual(values = "#C3107E")

ggplot(date_summary, aes(x = total_work_time)) + geom_histogram(binwidth = 1, color = "white") + labs(
  title = "Histogram of homework hours by date"
)

```


```{r}
ggplot(calendar_data, aes(x=hours)) + geom_histogram(binwidth = 0.5, color = "white") + facet_wrap(~summary)
```

```{r}
class_summary <- calendar_data %>% 
  group_by(summary) %>% 
  summarize(avg_class_time = mean(hours),
            median_class_time = median(hours),
            total_time = sum(hours)
            )
class_summary
```



```{r}
ggplot(class_summary, aes(x = summary, y = total_time)) + geom_col()
```


```{r}
calendar_data <- calendar_data %>% 
  group_by(date) %>% 
  arrange(date) %>% 
  mutate(week = ifelse(date < "2021-10-18", 1, 2))

week_summary <- calendar_data %>% 
  group_by(week) %>% 
  summarize(
    total_hours = sum(hours)
  )

ggplot(week_summary,  aes(x = factor(week), y = total_hours)) + geom_col()
```

