---
title: "Class_Timelog"
author: "Maeve Tyler-Penny"
output:
  pdf_document:
    toc: no
  html_document:
    toc: no
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, message=FALSE}
library(dplyr)
library(lubridate)
library(ical)
library(wesanderson)
library(scales)
library(lubridate)
library(tidyverse)
library(ggiraph)
```
## Calendar Data
```{r, echo=FALSE, message=FALSE}
calendar_data <- "eek.ics" %>% 
  # Use ical package to import into R and then convert to "tibble" data frame format:
  ical_parse_df() %>% 
  as_tibble() %>% 
  # Use lubridate packge to wrangle dates and times. We'll do this later this semester:
  mutate(
    start_datetime = with_tz(start, tzone = "America/New_York"),
    end_datetime = with_tz(end, tzone = "America/New_York"),
    minutes = end_datetime - start_datetime,
    date = floor_date(start_datetime, unit = "day")
  ) %>%
  # Make calendar entry summary all lowercase:
  mutate(summary = tolower(summary)) %>% 
  # Do data wrangling to compute number of minutes and hours:
  group_by(date, summary) %>%
  summarize(minutes = sum(minutes) %>% as.numeric()) %>%
  mutate(hours = minutes/60) %>% 
  mutate(date = as.Date(date))
  calendar_data <- filter(calendar_data, date > 2000-01-01)
```

```{r, echo=FALSE}
calendar_data <- calendar_data %>% 
  mutate(week = cut(date, "week", start.on.monday = TRUE))

calendar_data <- calendar_data %>% 
  mutate(day_of_week = weekdays(date))

```

## Time split by class, date, and week
```{r, echo=FALSE}
ggplot(calendar_data, aes(x = date, y = hours, fill = summary)) + geom_col(
  position = position_dodge(preserve = "single")) + labs(
  x = "Date",
  y = "Hours",
  title = "Comparison of Class Work Hours",
  fill = "Class"
) +
  scale_fill_manual(
  values = c("#FF1053", "#11B5E4", "#8710A9", "#000000")) + facet_wrap(~week, ncol = 3, scales = "free_x")
```

## Class proportions by day
```{r, echo=FALSE}
ggplot(calendar_data, 
       aes(x = date, y = hours, fill = summary)) + 
  geom_col(position = "fill") + scale_fill_manual(
             values = c("#FF1053", "#11B5E4", "#8710A9", "#000000"))
```

## Distribution of time split by class
```{r, echo=FALSE}
ggplot(calendar_data, aes(x = hours, y = summary, fill = summary)) + 
  geom_boxplot() + 
  scale_fill_manual(values = c("#FF1053", "#11B5E4", "#8710A9", "#000000")) +
  labs(title = "Distribution of class hours",
       y = "class"
       )
```

## Distribution of total work hours by day
```{r, echo=FALSE}
date_summary <- calendar_data %>% 
  group_by(date) %>% 
  summarize(total_work_time = sum(hours))

date_summary


ggplot(date_summary, aes(x = total_work_time)) +
  geom_histogram(binwidth = 0.5, color = "white") +
  labs(
  title = "Histogram of school hours by date",
  x = "hours",
  y = "count"
)

hist(date_summary$total_work_time)

```

## Visualizations Five & Six
```{r, echo=FALSE}
ggplot(calendar_data, aes(x=hours)) + 
  geom_histogram(binwidth = 0.5, color = "white") + facet_wrap(~summary)

day_summary <- calendar_data %>% 
  group_by(day_of_week, summary) %>% 
  summarize(mean_time = mean(hours))

ggplot(day_summary, aes(x = day_of_week, y = mean_time, fill = summary)) + 
  geom_col() + 
  scale_fill_manual(values = c("#FF1053", "#11B5E4", "#8710A9", "#000000"))
```

## Week Summary
```{r, echo=FALSE}
class_summary <- calendar_data %>%
  group_by(summary) %>%
  summarize(avg_class_time = mean(hours),
            median_class_time = median(hours),
            total_time = sum(hours)
            )
```


```{r, echo=FALSE}
week_summary <- calendar_data %>% 
  group_by(week) %>% 
  summarize(
    total_hours = sum(hours)
  )

bar1 <- ggplot(week_summary,  aes(x = factor(week), y = total_hours, tooltip = total_hours, data_id = week)) + 
  # geom_col() +
  # theme(axis.text.x = element_text(angle=25)) +
  # labs(title = "School Hours by Week",
  #      x = "week",
  #      y = "hours") + 
  geom_col_interactive()

x <- girafe(ggobj = bar1)
if ( interactive() ) print(x)
```


## Code Sources
Lines 27-45 taken from Miniproject 1 code written by Albert Kim for SDS 192, 
Fall 2021.

